
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test-jpa
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update
    show-sql: true